### ISSUE TITLE
Suspected zeebe-client-java mismatch with new zeebe gateway version

### ISSUE THREAD

**Issue by afk11** [openMF/ph-ee-connector-channel#6]
A while ago ph-ee-env-template merged which bumped zeebe to 1.1.0 (https://github.com/openMF/ph-ee-env-template/pull/7) I wonder if the change was not simply rebranding/hosting in a new repo, it seems they changed some endpoints also?

I'm testing transfers from connector-channel, and when I send one, I get a Zeebe client error, that the grpc endpoint on zeebe server cannot be found (https://gist.github.com/afk11/fcca6ffbf7678f57928b010070d1883d):
`Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: gateway_protocol.Gateway/CreateWorkflowInstance`

It appears between 0.26.0 and 1.x they changed "Workflow" to "Process" which affected the routes. (https://stackoverflow.com/questions/68179311/cannot-create-process-instance-after-moving-to-camunda-cloud-lib) Based on that stackoverflow, the client should also be on 1.x series.

I'm not sure if this entirely solves it however - I tried this, and it didn't have a positive outcome. Instead of the request now succeeding, another issue appears during startup which prevents the HTTP server from starting. `java.lang.NoSuchMethodError: 'void io.netty.buffer.PooledByteBufAllocator.<init>(boolean, int, int, int, int, int, int, boolean)'`

```
zeebe-client-java   0.26.0 | 1.1.0
---------------------------------------------
io.grpc.grpc-netty: 1.34.0 | 1.38.1
io.netty.buffer:    4.1.43 | 4.1.43
```
It seems the same io.netty.buffer version is used by zeebe-client-java 0.26.0 and 1.1.0, though it's not being picked up any more - Has anyone ran into this?

**Comment by SubhamPramanik** [comment]
Hey @afk11 thanks for highlighting this. I've merged PR #7 to address the version mismatch issue.
